### ISSUE TITLE
Test, understand, document library behaviour on query exceptions and other error scenarios

### ISSUE THREAD

**Issue by hartmut-co-uk** [thriving-dev/kafka-streams-cassandra-state-store#13]
I want to know how the library / kstreams app behaves throughout the entire lifecycle when interaction with cassandra fails (Exception thrown, ...). Data loss through events being missed/skipped should be avoided. Data inconsistency (retries of non-idempotent processing logic) issues should be understood & documented. Also patterns on how to handle exceptions as part of the application code should be defined + documented. 

### Initial brainstorming of possible scenarios:
- query exception/error for writes
- query exception/error for reads
- cluster unavailable
- write blocked, cluster consistency cannot be fulfilled
- writing data fails (no MODIFY permission)
- creating tables fails (no CREATE permission)

### Tasks
- [ ] manual test, debugging, analysis
- [ ] write unit tests
- [ ] write documentation
- [ ] task out further / create follow-up issues
