### ISSUE TITLE
Improve correctness/completeness of library

### ISSUE THREAD

**Issue by hartmut-co-uk** [thriving-dev/kafka-streams-cassandra-state-store#14]
### Tasks
 - [x] ~wrap stores with `MeteredKeyValueStore` (builder)?~
 - [x] ~provide `timestampedKeyValueStore`~
 - [x] ~? (TBC) logging / caching is always disabled (because it's not implemented to wrap store by CassandraStores...)~
   - [x] ~always disable logging + caching?~

**Comment by hartmut-co-uk** [comment]
Analysed, nothing to do here.
