### ISSUE TITLE
IQv2 Support: Kafka ~3.7.0 included KIP-992, KIP-985, KIP-960, KIP-968

### ISSUE THREAD

**Issue by hartmut-co-uk** [thriving-dev/kafka-streams-cassandra-state-store#68]
### IQv2
Check out what's on the release train for IQv2.

- https://cwiki.apache.org/confluence/display/KAFKA/KIP-992%3A+Proposal+to+introduce+IQv2+Query+Types%3A+TimestampedKeyQuery+and+TimestampedRangeQuery
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-985%3A+Add+reverseRange+and+reverseAll+query+over+kv-store+in+IQv2
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-960%3A+Support+single-key_single-timestamp+interactive+queries+%28IQv2%29+for+versioned+state+stores
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-968%3A+Support+single-key_multi-timestamp+interactive+queries+%28IQv2%29+for+versioned+state+stores

### TODOs
- [ ] Understand the relevance of the KIPs for this library
- [ ] Create workable issues (user stories)

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/blob/main/CONTRIBUTING.md).
- [X] Check existing [discussions](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/discussions) and [issues](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/issues).
