### ISSUE TITLE
Benchmark cassandra state store(s)

### ISSUE THREAD

**Issue by hartmut-co-uk** [thriving-dev/kafka-streams-cassandra-state-store#70]
### Describe the feature

To understand and provide a baseline on the throughput a benchmark series should be planned, implemented, and results analysed.

### TODOs
- [ ] Streams use case(s) -> Kafka Streams topologies to benchmark
- [ ] Provide test data, and load producers
- [ ] Define (repeatable) infrastructure & stack(s)
- [ ] Get help with planning, reviewing, and implementing the benchmark series to ensure valuable and useful results 

### Final checks

- [X] Read the [contribution guide](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/blob/main/CONTRIBUTING.md).
- [X] Check existing [discussions](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/discussions) and [issues](https://github.com/thriving-dev/kafka-streams-cassandra-state-store/issues).
